const VAULT_KEY='kitcheck_vault_v2';const ITERATIONS=210000;const IDLE_MS=180000;
const TEMPLATES={collected:(c,e)=>`KitCheck — ${c.name} has been collected${e.by?' by '+e.by:''}${e.time?' at '+e.time:''}.`,waiting:(c)=>`KitCheck — ${c.name} is waiting at the collection point.`,notCollected:(c)=>`KitCheck — ${c.name} has not yet been collected.`,special:(c,e)=>`KitCheck — Special note for ${c.name}: ${e.note||'Confirm pickup.'}`,event:(c,e)=>`KitCheck — Event for ${c.name} on ${e.date||''}.`,location:(c,e)=>`KitCheck — Collection point: ${e.map||''}`};
const SEED=()=>{const today=isoDate(new Date());return{school:{name:'Blue & White Primary'},children:[{id:'c1',name:'Daniels De Lange',grade:'Grade 3',className:'3B',mom:{name:'Vicki',phone:'0820001101'},dad:{name:'Jaco De Lange',phone:'0820001102'},alt:{name:'Ouma',phone:'0820001103'},photo:'',print:null,notes:'',booked:today,photoConsent:true},{id:'c2',name:'Amara Nkosi',grade:'Grade 2',className:'2A',mom:{name:'Lerato Nkosi',phone:'0831112201'},dad:{name:'Thabo Nkosi',phone:'0831112202'},alt:{name:'',phone:''},photo:'',print:null,notes:'',booked:today,photoConsent:true},{id:'c3',name:'Liam Botha',grade:'Grade 1',className:'1C',mom:{name:'Susan Botha',phone:'0842223301'},dad:{name:'Pieter Botha',phone:'0842223302'},alt:{name:'Coach Riaan',phone:'0842223303'},photo:'',print:null,notes:'Sports Friday',booked:today,photoConsent:true}],duty:{},specials:[{id:'s1',childId:'c3',date:today,time:'13:15',type:'event-pickup',collector:'Coach Riaan',phone:'0842223303',note:'Field gate',status:'booked'}],notices:[],scans:[]};};
let state=null,cryptoKey=null,vaultMeta=null,dutyDate=isoDate(new Date()),filter='all',searchQ='',camStream=null,scanStream=null,lastFix=null,idleTimer=null,unlocked=false,lastScan=null;
function isoDate(d){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`;}
function nowTime(){const x=new Date();return `${String(x.getHours()).padStart(2,'0')}:${String(x.getMinutes()).padStart(2,'0')}`;}
function b64(buf){const bytes=buf instanceof ArrayBuffer?new Uint8Array(buf):buf;let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s);}
function unb64(str){const bin=atob(str);const out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('on');setTimeout(()=>el.classList.remove('on'),2800);}
function esc(s){return String(s??'').replace(/&/g,'&').replace(/</g,'<').replace(/>/g,'>').replace(/"/g,'"');}
async function deriveKey(pin,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pin),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:ITERATIONS,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encryptBytes(key,bytes){const iv=crypto.getRandomValues(new Uint8Array(12));const ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,bytes);return{iv:b64(iv),data:b64(ct)};}
async function decryptBytes(key,ivB64,dataB64){return crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(ivB64)},key,unb64(dataB64));}
function readVault(){try{const raw=localStorage.getItem(VAULT_KEY);return raw?JSON.parse(raw):null;}catch{return null;}}
async function sealState(){if(!cryptoKey||!state)return;const sealed=await encryptBytes(cryptoKey,new TextEncoder().encode(JSON.stringify(state)));localStorage.setItem(VAULT_KEY,JSON.stringify({version:2,algo:'AES-256-GCM',kdf:'PBKDF2-SHA-256',iterations:ITERATIONS,salt:vaultMeta.salt,iv:sealed.iv,ciphertext:sealed.data}));}
async function save(){if(!unlocked)return;try{await sealState();paintVaultStatus();}catch{toast('Vault write failed.');}}
async function createVault(pin){const salt=crypto.getRandomValues(new Uint8Array(16));cryptoKey=await deriveKey(pin,salt);vaultMeta={salt:b64(salt)};state=SEED();if(!state.scans)state.scans=[];unlocked=true;await sealState();}
async function unlockVault(pin){const pack=readVault();if(!pack)throw new Error('No vault');const key=await deriveKey(pin,unb64(pack.salt));const plain=await decryptBytes(key,pack.iv,pack.ciphertext);state=JSON.parse(new TextDecoder().decode(plain));if(!state.scans)state.scans=[];cryptoKey=key;vaultMeta={salt:pack.salt};unlocked=true;}
async function changePin(oldPin,newPin){await unlockVault(oldPin);const salt=crypto.getRandomValues(new Uint8Array(16));cryptoKey=await deriveKey(newPin,salt);vaultMeta={salt:b64(salt)};await sealState();}
function lockNow(){cryptoKey=null;state=null;unlocked=false;lastScan=null;stopCam();stopScanCam();document.getElementById('appShell').classList.add('hidden');document.getElementById('lockScreen').classList.remove('hidden');const hasVault=!!readVault();document.getElementById('lockTitle').textContent=hasVault?'Unlock KitCheck':'Create staff PIN';document.getElementById('lockHelp').textContent=hasVault?'Enter the duty PIN.':'Set a PIN of at least 6 characters.';document.getElementById('pin2wrap').classList.toggle('hidden',hasVault);document.getElementById('staffPin').value='';document.getElementById('staffPin2').value='';document.getElementById('staffPin').focus();}
function bumpIdle(){clearTimeout(idleTimer);if(!unlocked)return;idleTimer=setTimeout(lockNow,IDLE_MS);}
function paintVaultStatus(){const el=document.getElementById('vaultStatus');if(el)el.textContent=unlocked?'AES-256-GCM · unlocked':'locked';}
async function submitLock(ev){ev.preventDefault();const pin=document.getElementById('staffPin').value;const pin2=document.getElementById('staffPin2').value;const hasVault=!!readVault();if(pin.length<6)return toast('PIN must be at least 6 characters.');try{if(!hasVault){if(pin!==pin2)return toast('PINs do not match.');await createVault(pin);}else await unlockVault(pin);document.getElementById('lockScreen').classList.add('hidden');document.getElementById('appShell').classList.remove('hidden');paintVaultStatus();fillChildSelects();const dd=document.getElementById('dutyDate');if(dd)dd.value=dutyDate;const sd=document.getElementById('sdate');if(sd)sd.value=dutyDate;go('duty');bumpIdle();}catch{toast('Wrong PIN or damaged vault.');}}
function dutyFor(date){if(!state.duty[date])state.duty[date]={};return state.duty[date];}
function childStatus(child,date){return dutyFor(date)[child.id]||{status:'at-school',by:'',time:'',note:''};}
function initials(name){return (name||'?').split(' ').filter(Boolean).slice(0,2).map(p=>p[0].toUpperCase()).join('');}
function childById(id){return state.children.find(c=>c.id===id);}
function waLink(phone,text){const n=String(phone||'').replace(/\D/g,'');if(!n)return null;const intl=n.startsWith('0')&&n.length===10?'27'+n.slice(1):n;return `https://wa.me/${intl}?text=${encodeURIComponent(text)}`;}
function go(page){if(!unlocked)return;document.querySelectorAll('.page').forEach(p=>p.classList.toggle('on',p.dataset.page===page));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===page));const titles={duty:['Duty board','Nobody leaves unmarked.'],register:['Learner register','Photos and parents.'],scan:['Biometric scan','Frame the face, then confirm.'],specials:['Specials','Once-off and events.'],notify:['Updates','WhatsApp, email, location.'],clauses:['Clauses','Vault and gate rules.']};document.getElementById('pageTitle').textContent=titles[page][0];document.getElementById('pageSub').textContent=titles[page][1];if(page!=='scan')stopScanCam();if(page!=='register')stopCam();if(page==='duty')renderDuty();if(page==='register')renderRegister();if(page==='scan')renderScan();if(page==='specials')renderSpecials();if(page==='notify')renderNotify();}
function photoEl(child,cls){if(child.photo)return `<img class="photo ${cls||''}" src="${child.photo}" alt="">`;return `<div class="photo empty ${cls||''}">${initials(child.name)}</div>`;}
function renderDuty(){const list=state.children.filter(c=>{const q=searchQ.trim().toLowerCase();if(q&&!`${c.name} ${c.grade}`.toLowerCase().includes(q))return false;const st=childStatus(c,dutyDate).status;if(filter==='collected')return st==='collected';if(filter==='open')return st!=='collected';if(filter==='waiting')return st==='waiting'||st==='at-school';return true;});const counts={total:state.children.length,collected:0,waiting:0,open:0};state.children.forEach(c=>{const st=childStatus(c,dutyDate).status;if(st==='collected')counts.collected++;else if(st==='waiting')counts.waiting++;else counts.open++;});const pct=counts.total?Math.round(counts.collected/counts.total*100):0;document.getElementById('stats').innerHTML=`<div class="stat"><div class="label">On register</div><div class="num">${counts.total}</div></div><div class="stat ok"><div class="label">Collected</div><div class="num">${counts.collected}</div></div><div class="stat wait"><div class="label">Waiting</div><div class="num">${counts.waiting}</div></div><div class="stat alert"><div class="label">Still at school</div><div class="num">${counts.open}</div></div>`;const dp=document.getElementById('dutyProgress');if(dp)dp.innerHTML=`<div class="panel" style="padding:14px 18px"><div style="display:flex;justify-content:space-between"><span>Complete</span><strong>${pct}%</strong></div><div class="progress"><span style="width:${pct}%"></span></div></div>`;const host=document.getElementById('dutyGrid');host.innerHTML=`<div class="grid">${list.map(c=>dutyCard(c)).join('')}</div>`;}
function dutyCard(c){const rec=childStatus(c,dutyDate);const badge=rec.status==='collected'?`<span class="badge b-ok">Collected</span>`:rec.status==='waiting'?`<span class="badge b-wait">Waiting</span>`:`<span class="badge b-school">At school</span>`;return `<article class="card"><div class="card-head">${photoEl(c)}<div><div class="kid-name">${esc(c.name)}</div><div class="kid-meta">${esc(c.grade)} · ${esc(c.className)}</div><div class="badges">${badge}${c.print?'<span class="badge b-scan">Scan enrolled</span>':''}</div></div></div><div class="card-body"><div>Mom <strong>${esc(c.mom.phone)}</strong></div><div>Dad <strong>${esc(c.dad.phone)}</strong></div></div><div class="card-actions"><button class="btn btn-wait btn-sm" onclick="mark('${c.id}','waiting')">Waiting</button><button class="btn btn-ok btn-sm" onclick="askCollect('${c.id}')">Collected</button><button class="btn btn-ghost btn-sm" onclick="openScanFor('${c.id}')">Scan</button><button class="btn btn-ghost btn-sm" onclick="quickNotify('${c.id}')">Notify</button></div></article>`;}
function mark(id,status){dutyFor(dutyDate)[id]={status,by:status==='waiting'?'Collection point':'',time:nowTime(),note:''};save();renderDuty();toast(childById(id).name+' marked '+status);}
function askCollect(id){const c=childById(id);const def=c.mom.name||c.dad.name||'';openModal('Confirm collection',`<label>Released to</label><input id="collectBy" type="text" value="${esc(def)}">`,()=>{const by=document.getElementById('collectBy').value.trim();if(!by)return toast('Enter collector');dutyFor(dutyDate)[id]={status:'collected',by,time:nowTime(),note:''};save();closeModal();renderDuty();});}
function renderRegister(){const host=document.getElementById('regList');if(!host)return;host.innerHTML=`<div class="grid">${state.children.map(c=>`<article class="card"><div class="card-head">${photoEl(c)}<div><div class="kid-name">${esc(c.name)}</div><div class="kid-meta">${esc(c.grade)}</div></div></div><div class="card-actions"><button class="btn btn-ghost btn-sm" onclick="editChild('${c.id}')">Edit</button><button class="btn btn-ghost btn-sm" onclick="openScanFor('${c.id}')">Scan</button><button class="btn btn-alert btn-sm" onclick="wipePhoto('${c.id}')">Wipe photo</button></div></article>`).join('')}</div>`;}
function resetChildForm(c){['cid','cname','cgrade','cclass','cbook','cmom','cmomph','cdad','cdadph','calt','caltph','cnotes','cphoto'].forEach(id=>{const el=document.getElementById(id);if(!el)return;});if(!document.getElementById('cid'))return;document.getElementById('cid').value=c?.id||'';document.getElementById('cname').value=c?.name||'';document.getElementById('cgrade').value=c?.grade||'';document.getElementById('cclass').value=c?.className||'';document.getElementById('cbook').value=c?.booked||'';document.getElementById('cmom').value=c?.mom?.name||'';document.getElementById('cmomph').value=c?.mom?.phone||'';document.getElementById('cdad').value=c?.dad?.name||'';document.getElementById('cdadph').value=c?.dad?.phone||'';document.getElementById('calt').value=c?.alt?.name||'';document.getElementById('caltph').value=c?.alt?.phone||'';document.getElementById('cnotes').value=c?.notes||'';document.getElementById('cphoto').value=c?.photo||'';const box=document.getElementById('cconsent');if(box)box.checked=!!c?.photoConsent;const prev=document.getElementById('photoPreview');if(prev){if(c?.photo){prev.src=c.photo;prev.classList.remove('hidden');}else{prev.classList.add('hidden');}}}
function editChild(id){resetChildForm(childById(id));go('register');}
function wipePhoto(id){const c=childById(id);c.photo='';c.print=null;save();renderRegister();}
async function saveChild(ev){ev.preventDefault();const id=document.getElementById('cid').value||('c'+Date.now());const photo=document.getElementById('cphoto').value;const rec={id,name:document.getElementById('cname').value.trim(),grade:document.getElementById('cgrade').value.trim(),className:document.getElementById('cclass').value.trim(),booked:document.getElementById('cbook').value,mom:{name:document.getElementById('cmom').value.trim(),phone:document.getElementById('cmomph').value.trim()},dad:{name:document.getElementById('cdad').value.trim(),phone:document.getElementById('cdadph').value.trim()},alt:{name:document.getElementById('calt').value.trim(),phone:document.getElementById('caltph').value.trim()},notes:document.getElementById('cnotes').value.trim(),photo,print:photo?await facePrint(photo):null,photoConsent:!!document.getElementById('cconsent')?.checked};if(!rec.name)return toast('Name required');if(rec.photo&&!rec.photoConsent)return toast('Consent required');const i=state.children.findIndex(x=>x.id===id);if(i>=0)state.children[i]={...state.children[i],...rec};else state.children.push(rec);save();resetChildForm(null);renderRegister();}
async function startCam(){try{stopCam();camStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});const v=document.getElementById('cam');v.srcObject=camStream;v.style.display='block';v.classList.remove('hidden');await v.play();}catch{toast('Camera blocked');}}
function stopCam(){if(camStream){camStream.getTracks().forEach(t=>t.stop());camStream=null;}const v=document.getElementById('cam');if(v){v.style.display='none';v.classList.add('hidden');}}
function captureCam(){const v=document.getElementById('cam');if(!v||v.readyState<2)return toast('Start camera');setPhoto(grabSquare(v));stopCam();}
function onPhotoFile(ev){const file=ev.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>setPhoto(r.result);r.readAsDataURL(file);}
function setPhoto(data){document.getElementById('cphoto').value=data;const prev=document.getElementById('photoPreview');prev.src=data;prev.classList.remove('hidden');}
function grabSquare(video){const canvas=document.createElement('canvas');canvas.width=360;canvas.height=360;const ctx=canvas.getContext('2d');const side=Math.min(video.videoWidth,video.videoHeight);ctx.drawImage(video,(video.videoWidth-side)/2,(video.videoHeight-side)/2,side,side,0,0,360,360);return canvas.toDataURL('image/jpeg',0.84);}
function facePrint(dataUrl){return new Promise(resolve=>{const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=32;c.height=32;const ctx=c.getContext('2d');ctx.drawImage(img,0,0,32,32);const d=ctx.getImageData(0,0,32,32).data;const vec=[];for(let i=0;i<d.length;i+=4)vec.push((0.299*d[i]+0.587*d[i+1]+0.114*d[i+2])/255);const mean=vec.reduce((a,b)=>a+b,0)/vec.length;resolve(vec.map(v=>Math.round((v-mean)*1000)/1000));};img.onerror=()=>resolve(null);img.src=dataUrl;});}
function cosine(a,b){if(!a||!b||a.length!==b.length)return 0;let dot=0,na=0,nb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];na+=a[i]*a[i];nb+=b[i]*b[i];}return dot/(Math.sqrt(na)*Math.sqrt(nb)+1e-8);}
function frameEnergy(video){const c=document.createElement('canvas');c.width=48;c.height=48;c.getContext('2d').drawImage(video,0,0,48,48);const d=c.getContext('2d').getImageData(0,0,48,48).data;let s=0;for(let i=0;i<d.length;i+=16)s+=d[i];return s;}
function renderScan(){const s=document.getElementById('scanStatus');if(s)s.textContent=scanStream?'Camera live':'Start the scan camera.';paintMatches();}
async function startScanCam(){try{stopScanCam();scanStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});const v=document.getElementById('scanCam');v.srcObject=scanStream;await v.play();document.getElementById('scanStatus').textContent='Centre the face in the oval.';}catch{toast('Camera denied');}}
function stopScanCam(){if(scanStream){scanStream.getTracks().forEach(t=>t.stop());scanStream=null;}}
async function runScan(){const v=document.getElementById('scanCam');if(!scanStream||!v||v.readyState<2){await startScanCam();return toast('Camera starting — scan again.');}const e1=frameEnergy(v);await new Promise(r=>setTimeout(r,280));const e2=frameEnergy(v);const live=Math.abs(e1-e2)>40;const shot=grabSquare(v);const print=await facePrint(shot);const ranked=state.children.filter(c=>c.print&&c.photo).map(c=>({child:c,score:cosine(print,c.print)})).sort((a,b)=>b.score-a.score).slice(0,4);lastScan={shot,print,live,ranked,at:isoDate(new Date())+' '+nowTime()};const snap=document.getElementById('scanSnap');snap.src=shot;snap.classList.remove('hidden');const flag=document.getElementById('liveFlag');flag.textContent=live?'Live frame change':'Little motion — check printed photo';flag.className='badge '+(live?'b-ok':'b-wait');paintMatches();}
function paintMatches(){const box=document.getElementById('matchBox');if(!box)return;if(!lastScan){box.innerHTML='<div class="empty">No scan yet.</div>';return;}if(!lastScan.ranked.length){box.innerHTML='<div class="empty">Enrol a consented photo on Register first.</div>';return;}box.innerHTML=lastScan.ranked.map(({child:c,score})=>{const pct=Math.max(0,Math.round(score*100));return `<div style="display:flex;gap:12px;align-items:center;padding:10px 0">${photoEl(c)}<div style="flex:1"><div class="kid-name">${esc(c.name)}</div><div class="kid-meta">${pct}% match</div></div><button class="btn btn-ok btn-sm" onclick="confirmScan('${c.id}')">Confirm</button></div>`;}).join('');}
function confirmScan(id){const c=childById(id);state.scans.push({at:lastScan?.at,childId:id,name:c.name});dutyFor(dutyDate)[id]={status:'waiting',by:'Scan confirmed',time:nowTime(),note:'Biometric photo scan'};save();toast(c.name+' confirmed');go('duty');}
function openScanFor(id){go('scan');startScanCam();}
function labelType(t){return { 'special-pickup':'Special pickup','event-pickup':'Event pickup','event-drop':'Event drop-off',aftercare:'Aftercare',early:'Early collection'}[t]||t;}
function renderSpecials(){const host=document.getElementById('specialTable');if(!host)return;host.innerHTML=state.specials.map(s=>`<div>${esc(s.date)} · ${esc(childById(s.childId)?.name)} · ${labelType(s.type)} · ${esc(s.collector)}</div>`).join('')||'<div class="empty">None</div>';}
function saveSpecial(ev){ev.preventDefault();state.specials.push({id:'s'+Date.now(),childId:document.getElementById('schild').value,date:document.getElementById('sdate').value,time:document.getElementById('stime').value,type:document.getElementById('stype').value,collector:document.getElementById('swho').value.trim(),phone:document.getElementById('sph').value.trim(),note:document.getElementById('snote').value.trim(),status:'booked'});save();renderSpecials();fillChildSelects();}
function delSpecial(id){state.specials=state.specials.filter(s=>s.id!==id);save();renderSpecials();}
function renderNotify(){fillChildSelects();const log=document.getElementById('noticeLog');if(log)log.innerHTML=state.notices.slice().reverse().slice(0,20).map(n=>`<div>${esc(n.at)} · ${esc(n.child)} · ${esc(n.channel)}</div>`).join('')||'<div class="empty">No notices</div>';}
function buildMessage(){const id=document.getElementById('nchild').value;const kind=document.getElementById('nkind').value;const c=childById(id)||{name:'the learner'};const rec=id?childStatus(c,dutyDate):{};return (TEMPLATES[kind]||TEMPLATES.waiting)(c,{by:rec.by,time:rec.time,note:document.getElementById('nnote')?.value||'',date:dutyDate,map:lastFix?lastFix.maps:'[no pin]'});}
function previewMsg(){const el=document.getElementById('npreview');if(el)el.value=buildMessage();}
function sendNotice(channel){const id=document.getElementById('nchild').value;const c=childById(id);if(!c)return toast('Select a learner');const text=document.getElementById('npreview').value.trim()||buildMessage();const who=document.getElementById('nwho').value;const phone=who==='dad'?c.dad.phone:who==='alt'?c.alt.phone:c.mom.phone;if(channel==='whatsapp'||channel==='both'){const link=waLink(phone||c.dad.phone,text);if(link)window.open(link,'_blank');}if(channel==='email'||channel==='both')window.open(`mailto:?subject=${encodeURIComponent('KitCheck — '+c.name)}&body=${encodeURIComponent(text)}`,'_blank');state.notices.push({at:isoDate(new Date())+' '+nowTime(),child:c.name,channel,kind:document.getElementById('nkind').value});save();renderNotify();}
function quickNotify(id){go('notify');document.getElementById('nchild').value=id;previewMsg();}
function shareLocation(){if(!navigator.geolocation)return toast('No location');navigator.geolocation.getCurrentPosition(pos=>{lastFix={maps:`https://maps.google.com/?q=${pos.coords.latitude},${pos.coords.longitude}`};document.getElementById('locBox').innerHTML=`<a href="${lastFix.maps}" target="_blank">Open map</a>`;document.getElementById('nkind').value='location';previewMsg();},()=>toast('Location denied'));}
function shareLocWhatsApp(){if(!lastFix)return shareLocation();const first=state.children[0];const link=waLink(first?.dad?.phone||first?.mom?.phone,TEMPLATES.location({name:"duty"},{map:lastFix.maps}));if(link)window.open(link,'_blank');}
function fillChildSelects(){if(!state)return;const opts=state.children.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');['schild','nchild'].forEach(id=>{const el=document.getElementById(id);if(!el)return;el.innerHTML=opts;});}
function uncollectedReport(){const open=state.children.filter(c=>childStatus(c,dutyDate).status!=='collected');toast(open.length?open.map(c=>c.name).join(', '):'All collected');}
function openModal(title,html,onOk){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=html;document.getElementById('modalOk').onclick=onOk;document.getElementById('modal').classList.add('on');}
function closeModal(){document.getElementById('modal').classList.remove('on');}
function exportDay(){const lines=[`KitCheck ${dutyDate}`].concat(state.children.map(c=>{const r=childStatus(c,dutyDate);return `${c.name} | ${r.status} | ${r.by||''}`; }));const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([lines.join('\n')]));a.download=`KitCheck-${dutyDate}.txt`;a.click();}
async function submitChangePin(ev){ev.preventDefault();const n=document.getElementById('newPin').value;if(n!==document.getElementById('newPin2').value)return toast('Mismatch');try{await changePin(document.getElementById('oldPin').value,n);toast('PIN changed');}catch{toast('Wrong current PIN');}}
window.addEventListener('DOMContentLoaded',()=>{document.getElementById('lockForm').addEventListener('submit',submitLock);const d=document.getElementById('dutyDate');if(d)d.addEventListener('change',e=>{dutyDate=e.target.value||isoDate(new Date());renderDuty();});const q=document.getElementById('q');if(q)q.addEventListener('input',e=>{searchQ=e.target.value;renderDuty();});['click','keydown'].forEach(ev=>document.addEventListener(ev,bumpIdle,{passive:true}));lockNow();});
